# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0053_auto_20160414_0551'),
        ('wishlist', '0002_auto_20160419_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whishlist',
            name='product',
        ),
        migrations.AddField(
            model_name='whishlist',
            name='product',
            field=models.ManyToManyField(to='products.Products'),
        ),
    ]
