# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0005_auto_20160419_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whishlist',
            options={'verbose_name': 'wishlist', 'verbose_name_plural': 'wishlist'},
        ),
        migrations.AlterField(
            model_name='whishlist',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
