# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0007_auto_20160420_1423'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Whishlist',
            new_name='Wishlist',
        ),
        migrations.AlterModelTable(
            name='wishlist',
            table='db_wishlist',
        ),
    ]
