# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name': 'Brands', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Images', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Products', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
