# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20160329_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='old_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
