# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20160329_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='url',
            field=models.ImageField(max_length=500, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
