# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20160330_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='cover',
            field=models.IntegerField(blank=True, choices=[(1, 'cover'), ('0', 'non cover')]),
        ),
    ]
