# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20160330_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='cover',
        ),
    ]
