# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_images_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='cover',
            field=models.BooleanField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='images',
            unique_together=set([('product', 'cover')]),
        ),
    ]
