# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20160331_0711'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='images',
            unique_together=set([('cover', 'product')]),
        ),
    ]
