# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20160331_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='cover',
            field=models.BooleanField(),
        ),
        migrations.AlterUniqueTogether(
            name='images',
            unique_together=set([]),
        ),
    ]
