# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_remove_images_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='cover',
            field=models.ImageField(default=1, max_length=300, upload_to='covers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='images',
            name='url',
            field=models.ImageField(max_length=300, upload_to='images'),
        ),
    ]
