# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_auto_20160331_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='visible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
