# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_auto_20160401_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='old_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
