# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_auto_20160401_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
