# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_auto_20160401_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='cover',
            field=imagekit.models.fields.ProcessedImageField(default=1, upload_to='covers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
