# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_auto_20160403_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
    ]
