# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_auto_20160413_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, default='', max_digits=7),
        ),
    ]
