# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 15:24
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0053_auto_20160414_0551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-id'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='products',
            name='cover',
            field=imagekit.models.fields.ProcessedImageField(max_length=600, upload_to='covers'),
        ),
    ]
