# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0054_auto_20160426_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category_slug',
            field=models.SlugField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
