# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0055_products_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category_slug',
        ),
    ]
